chore: 拆解工作流文件

diff --git a/.github/actions/build-tauri/action.yml b/.github/actions/build-tauri/action.yml
--- a/.github/actions/build-tauri/action.yml
+++ b/.github/actions/build-tauri/action.yml
@@ -29,11 +29,11 @@ runs:
       shell: bash
       run: |
         export PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"
-        # 安装javascriptcoregtk-4.0依赖
+        # 安装javascriptcoregtk-4.1依赖
         sudo apt-get update
-        sudo apt-get install -y libjavascriptcoregtk-4.0-dev
-        # 确保javascriptcoregtk-4.0能被正确找到
-        pkg-config --exists javascriptcoregtk-4.0 || echo "javascriptcoregtk-4.0 not found in PKG_CONFIG_PATH"
+        sudo apt-get install -y libjavascriptcoregtk-4.1-dev
+        # 确保javascriptcoregtk-4.1能被正确找到
+        pkg-config --exists javascriptcoregtk-4.1 || echo "javascriptcoregtk-4.1 not found in PKG_CONFIG_PATH"
         yarn tauri build --target ${{ inputs.rust-target }}
       env:
         CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: "true"
